name: My workflow test
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: master
jobs:
  say_something:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is a test
      - run: pwd
      - run: ls /home/runner/work/bililiteRange/bililiteRange

